# -*- coding: utf-8 -*-
"""ICMP Client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVhOfZB-0_qtybiKrsd_T0zrEeH3ipPA
"""

#Hide info in echo request/reply
#normally 32 bits per packet
#Up to 1472 bytes per payload

#icmpsh C2

#icmpdoor C2

#Design to match normal ping traffic


from scapy.all import IP, ICMP, send, Raw
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.primitives import hashes
import time


def generate_key():
  key = Fernet.generate_key()
  encrypted_key = public_key.encrypt(key, padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()), algorithm=hashes.SHA256, label=None))
  return encrypted_key

def encode_message(message, key):
  f = Fernet(key)
  encoded = message.encode()
  encrypted_message = f.encrypt(encoded)
  return encrypted_message

def send_key(target_ip, key):
  packet = IP(dst=target_ip)/ICMP()/Raw(load=b"KEY:" + key)
  send(packet, verbose=0)
  time.sleep(0.2)

def create_packet(target_ip, encrypted):
    packet = IP(dst=target_ip)/ICMP()/Raw(load=b"MSG:" + encrypted)
    send(packet, verbose=0)
    time.sleep(0.2)
    return "Packet sent complete"

def main():
  print("Enter message: ")
  message = input()
  print("Enter target IP: ")
  target_ip = input()
  key = generate_key()
  send_key(target_ip, key)
  print("Sent key to server")
  encrypted = encode_message(message, key)
  create_packet(target_ip, encrypted)
  print("Sent packet to Server")

if(__name__ == "__main__"):
  main()