# -*- coding: utf-8 -*-
"""ICMP Server

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqDwu70uKBprIbYDE1ZQJ8gwAXc90uoV
"""

#idk how to implement on blue team infra

from scapy.all import *
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import hashes
from cryptography.fernet import Fernet

private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
public_key = private_key.public_key()

def get_packets(packet):
  global key

  if packet.haslayer(ICMP) and packet.haslayer(Raw):
    payload = packet[Raw].load

    if payload.startswith(b"KEY:"):
      encrypted_key = payload[4:]

      key = private_key.decrypt(encrypted_key, padding.OAEP(mgf=padding.MGF1(algorithm=hashes.SHA256()),algorithm=hashes.SHA256(), label=None))

    elif payload.startswith(b"MSG:") and key:
      encrypted_message = payload[4:]
      f = Fernet(key)
      decrypted_message = f.decrypt(encrypted_message).decode()

sniff(filter="icmp", prn=get_packets)